### ISSUE TITLE
引入全局.scss文件报错，.sass 确没问题？

### ISSUE THREAD

**Issue by zfy108** [kaola-fed/megalo#227]
![image](https://user-images.githubusercontent.com/20158770/54984907-cce4d080-4fea-11e9-976a-e57f9c0bebde.png)

**Comment by Airkro** [comment]
scss文件必须使用scss语法，不能用sass语法。先检查代码

**Comment by zfy108** [comment]
@Airkro 
用的就是scss语法，在mpvue里是没问题的，迁移到megalo全局引用这个文件就一直报这个错。

**Comment by bigmeow** [comment]
假设我有两个scss文件,都在scr/style目录下:
``` js
src/style/app.scss          小程序的全局样式
src/style/global-var.scss   sass的全局变量，里面定义的变量在其它scss文件中可直接使用
```

global-var 的代码:
``` scss
$env: 'development';
```
app.scss 的代码
``` scss
view {
  @if $env == 'development' {background: red;}
  @if $env == 'production' {background: blue;}
}
```

接下来，我们在 megalo.config.js 文件中设置:

``` js
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        // https://github.com/webpack-contrib/sass-loader
        data: `@import './style/global-var.scss';`
      }
    }
  }
}
```

这样你就可以在你的app.scss 里使用 global-var.scss 定义的变量了

接下来我们在 App.vue 文件里，引入 app.scss ，即可让样式打包到app,wxss 里

``` html
<style lang="scss">
@import './style/app.scss'
</style>
```

ps:  megalo-target 升级到最新版本
