### ISSUE TITLE
css作用域问题

### ISSUE THREAD

**Issue by LiangFuzhi** [kaola-fed/megalo#290]
```html
<template>
  <block>
      <div  class="btn">
        <slot>
          <mp-scale :scale="scale">
            <div class="flex">+</div>
          </mp-scale>
        </slot>
      </div>
    </block>
</template>
```
```css
<style lang="less" scoped>
.btn {
  width: 100%;
  height: 100%;
}
.flex {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
```
css作用域有问题
![image](https://user-images.githubusercontent.com/17739890/62683136-58865900-b9f0-11e9-96d8-4d721682c88a.png)
flex不生效，这种写法应该生效才对

```html
<template>
  <block>
      <div  class="btn">
          <mp-scale :scale="scale">
            <div class="flex">+</div>
          </mp-scale>
      </div>
    </block>
</template>
```
这样子flex就生效了
