### ISSUE TITLE
megalo没有做postcss处理么？

### ISSUE THREAD

**Issue by luanwulin** [kaola-fed/megalo#39]
mpvue里面可以正常些less，有postcss处理不规范的写法，
```css
/* 被清理 */
* {
  margin: 100px
}
```
就会被自动清理，但是megalo会报错，，，
